// Code generated by mockery v1.0.0. DO NOT EDIT.

// Copyright (c) 2021 The Jaeger Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


package mocks

import (
	context "context"

	elastic "github.com/olivere/elastic/v7"
	mock "github.com/stretchr/testify/mock"

	es "github.com/jaegertracing/jaeger/pkg/es"
)

// ScrollService is an autogenerated mock type for the ScrollService type
type ScrollService struct {
	mock.Mock
}

// Clear provides a mock function with given fields: ctx
func (_m *ScrollService) Clear(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Do provides a mock function with given fields: ctx
func (_m *ScrollService) Do(ctx context.Context) ([]*elastic.SearchHit, error) {
	ret := _m.Called(ctx)

	var r0 []*elastic.SearchHit
	if rf, ok := ret.Get(0).(func(context.Context) []*elastic.SearchHit); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*elastic.SearchHit)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Query provides a mock function with given fields: query
func (_m *ScrollService) Query(query elastic.Query) es.ScrollService {
	ret := _m.Called(query)

	var r0 es.ScrollService
	if rf, ok := ret.Get(0).(func(elastic.Query) es.ScrollService); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(es.ScrollService)
		}
	}

	return r0
}
